<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Certificate Type_ATCGlobalTheme_wt144_7e6273</name>
   <tag></tag>
   <elementGuidId>f6329ee1-c6bb-4c64-9c3b-48154d9b37b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ATCGlobalTheme_wt144_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt51_block_wtColumn2_wtTableRecords1_ctl03_wt97']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ATCGlobalTheme_wt144_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt51_block_wtColumn2_wtTableRecords1_ctl03_wt97</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt144$block$wtMainContent$WebPatterns_wtMoreInfo$block$wtContent$WebPatterns_wt51$block$wtColumn2$wtTableRecords1$ctl03$wt97</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt144_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt51_block_wtColumn2_wtTableRecords1_ctl03_wt97</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>121</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('ATCGlobalTheme_wt144_block_wtMainContent_wt138', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ATCGlobalTheme_wt144_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt51_block_wtColumn2_wtTableRecords1_ctl03_wt97&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ATCGlobalTheme_wt144_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt51_block_wtColumn2_wtTableRecords1_ctl03_wt97']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ATCGlobalTheme_wt144_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt51_block_wtColumn2_wtTableRecords1']/tbody/tr/td/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
   </webElementXpaths>
</WebElementEntity>
