<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuiteforDatadriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1eceaf12-6167-4486-a8ae-a4503105036b</testSuiteGuid>
   <testCaseLink>
      <guid>329e1438-c4f6-4a50-9c16-3bce02b9882b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTest</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4a62d28e-eb79-4c0d-a392-5044773c6ce3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4a62d28e-eb79-4c0d-a392-5044773c6ce3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>21d7fa2b-ca5c-4d5d-91cd-5eeea036c07b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4a62d28e-eb79-4c0d-a392-5044773c6ce3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>33cb25fb-626e-4cd7-9a06-cd032fa47b8b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
