<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_Suite_Tawasal_Regression_HRForms_Negative_scenarios</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b6e52dce-c287-495a-b8b3-050821f3cc2b</testSuiteGuid>
   <testCaseLink>
      <guid>0f1de2ee-606c-4f70-8cb6-fd246228b153</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HR_Forms_Negative_Scenarios/NT_Tawasal_login_TC_1_Negative</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>64e20868-c4ea-40de-b44d-d687eb6ea835</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Negative_login_data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>64e20868-c4ea-40de-b44d-d687eb6ea835</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>7e6f6309-8916-4cc9-93d2-02579e612997</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>64e20868-c4ea-40de-b44d-d687eb6ea835</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>fcbdd383-7990-4700-80d3-dfac3a5152a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>061180b8-888d-43c0-89d4-21a06e91d59d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HR_Forms_Negative_Scenarios/NT_ResidenceInfotransfer_NaegativeTest</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>01ab8167-b493-47ba-9e6b-c26b13ffeb40</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test_Data_Negative</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>01ab8167-b493-47ba-9e6b-c26b13ffeb40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>oldpassportnum</value>
         <variableId>0f14e40d-6c63-47c5-990f-a0ca3b8295df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>01ab8167-b493-47ba-9e6b-c26b13ffeb40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>newpassportnum</value>
         <variableId>272971b3-a470-4c5f-b978-5b8b2b801148</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>01ab8167-b493-47ba-9e6b-c26b13ffeb40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>residencenum</value>
         <variableId>4dee2b1f-3b22-4aae-a939-82736827a187</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f330281-ab78-4269-8cd8-e824629fdc1d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HR_Forms_Negative_Scenarios/NT_LeaveRequest_TC_1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>371509d2-2917-4834-af0b-887b9a707fc7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3417356-e740-4215-9db1-96462d925ef7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HR_Forms_Negative_Scenarios/NT_PhoneInternetServiceRequest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bf1d63fd-b7e3-47c8-835f-015c3b85134e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HR_Forms_Negative_Scenarios/NT_ResidenceRenewal_TC</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>59f588b2-5662-4e1a-9503-cdc3ba82240a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HR_Forms_Negative_Scenarios/NT_SalaryCert-TC1</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e5ee3d84-45d6-470c-8e87-90c42b4cddbc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HR_Forms_Negative_Scenarios/NT_SickLeaveRequest_TC</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f033978e-190b-46dd-9fe6-b2c506a673dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HR_Forms_Negative_Scenarios/NT_Tawasal_HRForms_BC_TC_2</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e734c444-9d12-4e08-a7c5-9121f3ed6f92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HR_Forms_Negative_Scenarios/NT_Tawasal_login_TC_1_Negative</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e6f6309-8916-4cc9-93d2-02579e612997</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcbdd383-7990-4700-80d3-dfac3a5152a3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
