# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
-  master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker pull katalonstudio/katalon
  displayName: 'Pull katalon studio images'
- script: docker run -t --rm -v "$(pwd)":/katalon/katalon/source katalonstudio/katalon katalon-execute.sh -browserType="Firefox" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_5TC" -apikey="784be99d-43ea-4469-912f-1ac4aff9adf5" --config -proxy.option=MANUAL_CONFIG -proxy.server.type=HTTP
  displayName: 'Runnning Katalon Test Suites/TestSuite'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'JUnit Report' 
    targetPath: report/

