<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Notice Period_ATCGlobalTheme_wt75bloc_199ba7</name>
   <tag></tag>
   <elementGuidId>4546426f-0fd8-4329-bf63-3dfe602eaa5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ATCGlobalTheme_wt75_block_wtMainContent_WebPatterns_wtAdditionalInfo_block_wtContent_WebPatterns_wt109_block_wtColumn2_wttxtNoticePeriod']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ATCGlobalTheme_wt75_block_wtMainContent_WebPatterns_wtAdditionalInfo_block_wtContent_WebPatterns_wt109_block_wtColumn2_wttxtNoticePeriod</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt75$block$wtMainContent$WebPatterns_wtAdditionalInfo$block$wtContent$WebPatterns_wt109$block$wtColumn2$wttxtNoticePeriod</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt75_block_wtMainContent_WebPatterns_wtAdditionalInfo_block_wtContent_WebPatterns_wt109_block_wtColumn2_wttxtNoticePeriod</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>151</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Second ThemeGrid_Width2 SmartInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'ATCGlobalTheme_wt75_block_wtMainContent_WebPatterns_wtAdditionalInfo_block_wtContent_WebPatterns_wt109_block_wtColumn2_wttxtNoticePeriod','ATCGlobalTheme_wt75$block$wtMainContent$WebPatterns_wtAdditionalInfo$block$wtContent$WebPatterns_wt109$block$wtColumn2$wttxtNoticePeriod','Change','__OSVSTATE,',0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>OsLimitInput(this,event,20);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('ATCGlobalTheme_wt75_block_wtMainContent_wtPrint', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onoschange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'ATCGlobalTheme_wt75_block_wtMainContent_WebPatterns_wtAdditionalInfo_block_wtContent_WebPatterns_wt109_block_wtColumn2_wttxtNoticePeriod','ATCGlobalTheme_wt75$block$wtMainContent$WebPatterns_wtAdditionalInfo$block$wtContent$WebPatterns_wt109$block$wtColumn2$wttxtNoticePeriod','Change','__OSVSTATE,',osOnChangeTimerDelay);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>origvalue</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ATCGlobalTheme_wt75_block_wtMainContent_WebPatterns_wtAdditionalInfo_block_wtContent_WebPatterns_wt109_block_wtColumn2_wttxtNoticePeriod&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ATCGlobalTheme_wt75_block_wtMainContent_WebPatterns_wtAdditionalInfo_block_wtContent_WebPatterns_wt109_block_wtColumn2_wttxtNoticePeriod']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ATCGlobalTheme_wt75_block_wtMainContent_WebPatterns_wtAdditionalInfo_block_wtContent_WebPatterns_wt109_block_wtColumn2_wtNoticeContainer2']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
