<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_International Subscription_ATCGlobalT_f540a7</name>
   <tag></tag>
   <elementGuidId>6b16596d-0eb4-4139-b7aa-665ab4dcfc95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn1']/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn1_wt177</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt59$block$wtMainContent$WebPatterns_wtMoreInfo$block$wtContent$WebPatterns_wt36$block$wtColumn1$wt177</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn1_wt177</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>120</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('ATCGlobalTheme_wt59_block_wtMainContent_wt189', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn1_wt177&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn1_wt177']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn1']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
