<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Internet on Mobile 5 KD (100 GB  1000_9d2a5e</name>
   <tag></tag>
   <elementGuidId>cad65a40-ae94-41b8-b447-1af5e82df1d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn2']/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn2_wt93</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt59$block$wtMainContent$WebPatterns_wtMoreInfo$block$wtContent$WebPatterns_wt36$block$wtColumn2$wt93</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn2_wt93</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>121</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('ATCGlobalTheme_wt59_block_wtMainContent_wt189', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn2_wt93','ATCGlobalTheme_wt59$block$wtMainContent$WebPatterns_wtMoreInfo$block$wtContent$WebPatterns_wt36$block$wtColumn2$wt93','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn2_wt93&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn2_wt93']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ATCGlobalTheme_wt59_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt36_block_wtColumn2']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
