<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Annual_-1720092522_1</name>
   <tag></tag>
   <elementGuidId>61ecb7d1-257e-4790-84a8-62e34b53dbbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ATCGlobalTheme_wt30_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt231_block_wtColumn1_WebPatterns_wt116_block_wtColumn2_wt127']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ATCGlobalTheme_wt30_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt231_block_wtColumn1_WebPatterns_wt116_block_wtColumn2_wt127</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>-1720092522</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt30_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt231_block_wtColumn1_WebPatterns_wt116_block_wtColumn2_wt127</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>148</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('ATCGlobalTheme_wt30_block_wtMainContent_wtsubmitbutton', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'ATCGlobalTheme_wt30_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt231_block_wtColumn1_WebPatterns_wt116_block_wtColumn2_wt127','ATCGlobalTheme_wt30$block$wtMainContent$WebPatterns_wtMoreInfo$block$wtContent$WebPatterns_wt231$block$wtColumn1$WebPatterns_wt116$block$wtColumn2$wt127','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ATCGlobalTheme_wt30_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt231_block_wtColumn1_WebPatterns_wt116_block_wtColumn2_wt127&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ATCGlobalTheme_wt30_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt231_block_wtColumn1_WebPatterns_wt116_block_wtColumn2_wt127']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ATCGlobalTheme_wt30_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt231_block_wtColumn1_WebPatterns_wt116_block_wtColumn2_wtAnnual']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
