<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From Date_ATCGlobalTheme_wt119blockwt_bfe0c7</name>
   <tag></tag>
   <elementGuidId>7441c054-c338-4da7-a3c4-22291c2e8b2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ATCGlobalTheme_wt119_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt140_block_wtColumn2_wtHRFormTrainingRequest_FromDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt119$block$wtMainContent$WebPatterns_wtMoreInfo$block$wtContent$WebPatterns_wt140$block$wtColumn2$wtHRFormTrainingRequest_FromDate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>02-11-2020</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt119_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt140_block_wtColumn2_wtHRFormTrainingRequest_FromDate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>121</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Third Mandatory</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('ATCGlobalTheme_wt119_block_wtMainContent_wtSubmitbtn', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onoschange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'ATCGlobalTheme_wt119_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt140_block_wtColumn2_wtHRFormTrainingRequest_FromDate','ATCGlobalTheme_wt119$block$wtMainContent$WebPatterns_wtMoreInfo$block$wtContent$WebPatterns_wt140$block$wtColumn2$wtHRFormTrainingRequest_FromDate','Change','__OSVSTATE,',osOnChangeTimerDelay);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'ATCGlobalTheme_wt119_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt140_block_wtColumn2_wtHRFormTrainingRequest_FromDate','ATCGlobalTheme_wt119$block$wtMainContent$WebPatterns_wtMoreInfo$block$wtContent$WebPatterns_wt140$block$wtColumn2$wtHRFormTrainingRequest_FromDate','Change','__OSVSTATE,',0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MM-YYYY</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ATCGlobalTheme_wt119_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt140_block_wtColumn2_wtHRFormTrainingRequest_FromDate&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ATCGlobalTheme_wt119_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt140_block_wtColumn2_wtHRFormTrainingRequest_FromDate']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ATCGlobalTheme_wt119_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt140_block_wtColumn2_wtFromDate']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
