<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_debug.log_ATCGlobalTheme_wt171blockwt_476e1c</name>
   <tag></tag>
   <elementGuidId>3e2a5322-6abb-4180-a8c1-5a9a6a18b8aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and @name = 'ATCGlobalTheme_wt171$block$wtMainContent$wt250' and @id = 'ATCGlobalTheme_wt171_block_wtMainContent_wt250']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ATCGlobalTheme_wt171_block_wtMainContent_wt250']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ATCGlobalTheme_wt171_block_wtMainContent_wt250</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>var ret = confirm('Are you sure you want to send this request for Approval?');if( ret != true ) {return false;}if (OsPage_ClientValidate('ATCGlobalTheme_wt171_block_wtMainContent_wt250')) OsAjax(arguments[0] || window.event,'ATCGlobalTheme_wt171_block_wtMainContent_wt250','ATCGlobalTheme_wt171$block$wtMainContent$wt250','','__OSVSTATE,',''); return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt171$block$wtMainContent$wt250</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt171_block_wtMainContent_wt250</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>180</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Second Is_Default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ATCGlobalTheme_wt171_block_wtMainContent_wt250&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ATCGlobalTheme_wt171_block_wtMainContent_wt250']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ATCGlobalTheme_wt171_block_wtMainContent_wtSubmitContainer']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
