<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_ATCGlobalTheme_wt171blockwtMain_b80be9</name>
   <tag></tag>
   <elementGuidId>6812eeb7-fdc5-4d44-ad2b-5212b578a393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ATCGlobalTheme_wt171_block_wtMainContent_WebPatterns_wtRequestInfo_block_wtContent_WebPatterns_wt336_block_wtColumn2_WebPatterns_wt136_block_wtColumn2_wtEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ATCGlobalTheme_wt171_block_wtMainContent_WebPatterns_wtRequestInfo_block_wtContent_WebPatterns_wt336_block_wtColumn2_WebPatterns_wt136_block_wtColumn2_wtEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt171$block$wtMainContent$WebPatterns_wtRequestInfo$block$wtContent$WebPatterns_wt336$block$wtColumn2$WebPatterns_wt136$block$wtColumn2$wtEmail</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt171_block_wtMainContent_WebPatterns_wtRequestInfo_block_wtContent_WebPatterns_wt336_block_wtColumn2_WebPatterns_wt136_block_wtColumn2_wtEmail</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>124</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('ATCGlobalTheme_wt171_block_wtMainContent_wt174', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onoschange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'ATCGlobalTheme_wt171_block_wtMainContent_WebPatterns_wtRequestInfo_block_wtContent_WebPatterns_wt336_block_wtColumn2_WebPatterns_wt136_block_wtColumn2_wtEmail','ATCGlobalTheme_wt171$block$wtMainContent$WebPatterns_wtRequestInfo$block$wtContent$WebPatterns_wt336$block$wtColumn2$WebPatterns_wt136$block$wtColumn2$wtEmail','Change','__OSVSTATE,',osOnChangeTimerDelay);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'ATCGlobalTheme_wt171_block_wtMainContent_WebPatterns_wtRequestInfo_block_wtContent_WebPatterns_wt336_block_wtColumn2_WebPatterns_wt136_block_wtColumn2_wtEmail','ATCGlobalTheme_wt171$block$wtMainContent$WebPatterns_wtRequestInfo$block$wtContent$WebPatterns_wt336$block$wtColumn2$WebPatterns_wt136$block$wtColumn2$wtEmail','Change','__OSVSTATE,',0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ATCGlobalTheme_wt171_block_wtMainContent_WebPatterns_wtRequestInfo_block_wtContent_WebPatterns_wt336_block_wtColumn2_WebPatterns_wt136_block_wtColumn2_wtEmail&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ATCGlobalTheme_wt171_block_wtMainContent_WebPatterns_wtRequestInfo_block_wtContent_WebPatterns_wt336_block_wtColumn2_WebPatterns_wt136_block_wtColumn2_wtEmail']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ATCGlobalTheme_wt171_block_wtMainContent_WebPatterns_wtRequestInfo_block_wtContent_WebPatterns_wt336_block_wtColumn2_WebPatterns_wt136_block_wtColumn2']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
