<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From_ATCGlobalTheme_wt20blockwtMainCo_ece7b4</name>
   <tag></tag>
   <elementGuidId>84adb3df-edb1-454c-90d1-e54b823e793a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ATCGlobalTheme_wt20_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt266_block_wtColumn2_WebPatterns_wt115_block_wtColumn2_wtTravelAuthorization_TripFromDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ATCGlobalTheme_wt20_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt266_block_wtColumn2_WebPatterns_wt115_block_wtColumn2_wtTravelAuthorization_TripFromDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt20$block$wtMainContent$WebPatterns_wtMoreInfo$block$wtContent$WebPatterns_wt266$block$wtColumn2$WebPatterns_wt115$block$wtColumn2$wtTravelAuthorization_TripFromDate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>07-03-2021</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt20_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt266_block_wtColumn2_WebPatterns_wt115_block_wtColumn2_wtTravelAuthorization_TripFromDate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>150</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('ATCGlobalTheme_wt20_block_wtMainContent_wt32', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onoschange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'ATCGlobalTheme_wt20_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt266_block_wtColumn2_WebPatterns_wt115_block_wtColumn2_wtTravelAuthorization_TripFromDate','ATCGlobalTheme_wt20$block$wtMainContent$WebPatterns_wtMoreInfo$block$wtContent$WebPatterns_wt266$block$wtColumn2$WebPatterns_wt115$block$wtColumn2$wtTravelAuthorization_TripFromDate','Change','__OSVSTATE,',osOnChangeTimerDelay);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'ATCGlobalTheme_wt20_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt266_block_wtColumn2_WebPatterns_wt115_block_wtColumn2_wtTravelAuthorization_TripFromDate','ATCGlobalTheme_wt20$block$wtMainContent$WebPatterns_wtMoreInfo$block$wtContent$WebPatterns_wt266$block$wtColumn2$WebPatterns_wt115$block$wtColumn2$wtTravelAuthorization_TripFromDate','Change','__OSVSTATE,',0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MM-YYYY</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ATCGlobalTheme_wt20_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt266_block_wtColumn2_WebPatterns_wt115_block_wtColumn2_wtTravelAuthorization_TripFromDate&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ATCGlobalTheme_wt20_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt266_block_wtColumn2_WebPatterns_wt115_block_wtColumn2_wtTravelAuthorization_TripFromDate']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ATCGlobalTheme_wt20_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt266_block_wtColumn2_WebPatterns_wt115_block_wtColumn2']/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
