<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Passport No_ATCGlobalTheme_wt82blockw_2adf0c</name>
   <tag></tag>
   <elementGuidId>2fc2a1c2-b72f-444d-89a0-f8f7c3dda6dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ATCGlobalTheme_wt82_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt33_block_wtColumn1_WebPatterns_wt17_block_wtColumn2_wtFormResidenceRenewal_PassportNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ATCGlobalTheme_wt82_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt33_block_wtColumn1_WebPatterns_wt17_block_wtColumn2_wtFormResidenceRenewal_PassportNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt82$block$wtMainContent$WebPatterns_wtMoreInfo$block$wtContent$WebPatterns_wt33$block$wtColumn1$WebPatterns_wt17$block$wtColumn2$wtFormResidenceRenewal_PassportNo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ATCGlobalTheme_wt82_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt33_block_wtColumn1_WebPatterns_wt17_block_wtColumn2_wtFormResidenceRenewal_PassportNo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>147</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>First Mandatory</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('ATCGlobalTheme_wt82_block_wtMainContent_wtSubmitBtn', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ATCGlobalTheme_wt82_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt33_block_wtColumn1_WebPatterns_wt17_block_wtColumn2_wtFormResidenceRenewal_PassportNo&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ATCGlobalTheme_wt82_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt33_block_wtColumn1_WebPatterns_wt17_block_wtColumn2_wtFormResidenceRenewal_PassportNo']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ATCGlobalTheme_wt82_block_wtMainContent_WebPatterns_wtMoreInfo_block_wtContent_WebPatterns_wt33_block_wtColumn1_WebPatterns_wt17_block_wtColumn2']/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
